Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,33 +1,57 @@
-# .github/workflows/preview.yml
-name: Deploy PR previews
+name: Deploy Next.js PR Preview to Pages
 
 on:
   pull_request:
-    types:
-      - opened
-      - reopened
-      - synchronize
-      - closed
+    branches:
+      - '*'
 
-concurrency: preview-${{ github.ref }}
+permissions:
+  contents: read
+  pages: write
+  id-token: write
+
+concurrency:
+  group: "pages"
+  cancel-in-progress: false
 
 jobs:
-  deploy-preview:
-    runs-on: ubuntu-20.04
+  deploy:
+    runs-on: ubuntu-latest
     steps:
       - name: Checkout
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
+        with:
+          token: ${{ secrets.MAGIC_SECRET }}
 
-      - name: Install and Build
-        if: github.event.action != 'closed'
+      - name: Detect package manager
         run: |
-          npm install
-          npm run build
-          # Dacă directorul de ieșire este "out", poate fi necesar un pas suplimentar pentru a-l crea
-          # mkdir -p out
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_ENV
+            echo "command=install" >> $GITHUB_ENV
+            echo "runner=yarn" >> $GITHUB_ENV
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_ENV
+            echo "command=ci" >> $GITHUB_ENV
+            echo "runner=npx --no-install" >> $GITHUB_ENV
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
+
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20"
+          cache: ${{ env.manager }}
+
+      - name: Install dependencies
+        run: ${{ env.manager }} ${{ env.command }}
+
+      - name: Build with Next.js
+        run: ${{ env.runner }} next build
 
       - name: Deploy preview
         uses: rossjrw/pr-preview-action@v1
         with:
           github_token: ${{ secrets.MAGIC_SECRET }}
-          source-dir: ./out/
+          source-dir: .next
