Update prDeploymentLink.yml

diff --git a/.github/workflows/prDeploymentLink.yml b/.github/workflows/prDeploymentLink.yml
--- a/.github/workflows/prDeploymentLink.yml
+++ b/.github/workflows/prDeploymentLink.yml
@@ -15,26 +15,47 @@ concurrency:
   cancel-in-progress: false
 
 jobs:
-  deployment:
+  deploy:
+    permissions: write-all
     runs-on: ubuntu-latest
-
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          token: ${{ secrets.MAGIC_SECRET }}
+
+      - name: Detect package manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_ENV
+            echo "command=install" >> $GITHUB_ENV
+            echo "runner=yarn" >> $GITHUB_ENV
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_ENV
+            echo "command=ci" >> $GITHUB_ENV
+            echo "runner=npx --no-install" >> $GITHUB_ENV
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
 
       - name: Setup Node
-        uses: actions/setup-node@v3
+        uses: actions/setup-node@v4
         with:
-          node-version: 'lts/*'
-          cache: 'npm'
+          node-version: "20"
+          cache: ${{ env.manager }}
 
-      - name: Build
-        run: |
-          npm i
-          npm run build
-          npm run export
+      - name: Install dependencies
+        run: ${{ env.manager }} ${{ env.command }}
 
-      - name: Deploy
-        uses: peaceiris/actions-gh-pages@v3
+      - name: Build with Next.js
+        run: ${{ env.runner }} next build
+
+      - name: Build1 with Next.js
+        run: ${{ env.runner }} next export
+
+      - name: Deploy preview
+        uses: rossjrw/pr-preview-action@v1
         with:
-          deploy_key: $
-          publish_dir: ./out
+          token: ${{ secrets.MAGIC_SECRET }}
+          source-dir: out
